import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const basierCircle = localFont({
  src: [
    {
      path: "../public/fonts/BasierCircle/BasierCircle-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/BasierCircle/BasierCircle-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/BasierCircle/BasierCircle-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/BasierCircle/BasierCircle-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/BasierCircle/BasierCircle-Italic.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-basier-circle",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${basierCircle.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
